# Generated by Django 4.1 on 2022-08-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField()),
                ('adm_no', models.IntegerField()),
                ('department', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=15)),
                ('staff_adv_name', models.CharField(max_length=30)),
                ('staff_adv_id', models.CharField(max_length=30)),
            ],
        ),
    ]
