# Generated by Django 4.1 on 2022-08-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_presiding_officer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='presiding_officer',
        ),
    ]
