# Generated by Django 4.1 on 2022-08-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0003_delete_presiding_officer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_detail',
            old_name='staff_adv_fname',
            new_name='staff_adv_username',
        ),
    ]
