# Generated by Django 4.1 on 2022-08-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0004_rename_staff_adv_fname_student_detail_staff_adv_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('adm_no', models.IntegerField()),
                ('apply_position', models.CharField(max_length=30)),
                ('position_id', models.CharField(max_length=10)),
                ('candidate_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='election_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=30)),
                ('position_name', models.CharField(max_length=30)),
                ('depts', models.CharField(choices=[('CS', 'Computer Science'), ('EC', 'Electronics and Communications'), ('BT', 'Biotechnology'), ('ME', 'Mechanical'), ('MP', 'Mechanical Production'), ('All', 'All')], max_length=30)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('All', 'All')], max_length=30)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('All', 'All')], max_length=30)),
                ('degree', models.CharField(choices=[('M', 'M Tech'), ('B', 'B Tech'), ('All', 'All')], max_length=30)),
            ],
        ),
    ]
